package client_test

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/kumobase/kumo-go/client"
	"github.com/kumobase/kumo-go/codes"
	"github.com/kumobase/kumo-go/types"
)

// newTestServer spins up an httptest server with the supplied handler and
// returns a Client pointed at it. The Client is configured with a short
// timeout so a hung test doesn't block CI for minutes.
func newTestServer(t *testing.T, h http.HandlerFunc) (*client.Client, *httptest.Server) {
	t.Helper()
	srv := httptest.NewServer(h)
	t.Cleanup(srv.Close)
	c, err := client.New(srv.URL,
		client.WithAPIKey("kumo_sk_test"),
		client.WithHTTPClient(&http.Client{Timeout: 5 * time.Second}),
	)
	if err != nil {
		t.Fatalf("client.New: %v", err)
	}
	return c, srv
}

// writeStruct is a tiny helper for handlers to emit a StructureResponse.
func writeStruct(w http.ResponseWriter, status int, code, msg string, data any) {
	body := map[string]any{"message": msg}
	if code != "" {
		body["code"] = code
	}
	if data != nil {
		raw, _ := json.Marshal(data)
		body["data"] = json.RawMessage(raw)
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

// ── Construction validation ──────────────────────────────────────────

func TestNew_RequiresBaseURL(t *testing.T) {
	_, err := client.New("", client.WithAPIKey("kumo_sk_x"))
	if err == nil {
		t.Fatal("expected error for empty baseURL")
	}
}

func TestNew_RequiresAuth(t *testing.T) {
	_, err := client.New("http://example.com")
	if err == nil {
		t.Fatal("expected error when no auth provided")
	}
}

func TestNew_RejectsBothAuthModes(t *testing.T) {
	_, err := client.New("http://example.com",
		client.WithAPIKey("kumo_sk_x"),
		client.WithJWT("jwt"),
	)
	if err == nil {
		t.Fatal("expected error when both auth modes set")
	}
}

func TestNew_TrimsTrailingSlash(t *testing.T) {
	var seen string
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		seen = r.URL.Path
		writeStruct(w, 200, "", "ok", nil)
	})
	_, _, err := c.Apps().Get(context.Background(), 1)
	if err != nil {
		// 200 with no data field decodes to zero value — no error expected
		// (Apps.Get expects AppByIdResponse; we just want to assert the path)
	}
	if seen != "/api/v1/apps/1" {
		t.Errorf("path: got %q, want %q", seen, "/api/v1/apps/1")
	}
}

// ── Auth header injection ────────────────────────────────────────────

func TestAuth_APIKeyHeaderInjected(t *testing.T) {
	var got string
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		got = r.Header.Get("Authorization")
		writeStruct(w, 200, "", "ok", nil)
	})
	_, _, _ = c.Apps().Get(context.Background(), 1)
	if got != "Bearer kumo_sk_test" {
		t.Errorf("Authorization: got %q, want %q", got, "Bearer kumo_sk_test")
	}
}

func TestAuth_JWTHeaderInjected(t *testing.T) {
	var got string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		got = r.Header.Get("Authorization")
		writeStruct(w, 200, "", "ok", nil)
	}))
	defer srv.Close()
	c, err := client.New(srv.URL, client.WithJWT("eyJabc"))
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	_, _, _ = c.Apps().Get(context.Background(), 1)
	if got != "Bearer eyJabc" {
		t.Errorf("Authorization: got %q, want %q", got, "Bearer eyJabc")
	}
}

func TestAuth_UserAgentIncludesSDKVersion(t *testing.T) {
	var got string
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		got = r.Header.Get("User-Agent")
		writeStruct(w, 200, "", "ok", nil)
	})
	_, _, _ = c.Apps().Get(context.Background(), 1)
	if !contains(got, "kumo-go/0.2.0") {
		t.Errorf("User-Agent: got %q, expected to contain kumo-go/0.2.0", got)
	}
}

// ── Idempotency-Key auto-generation ──────────────────────────────────

func TestIdempotency_AutoGeneratedOnPOST(t *testing.T) {
	var key string
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		key = r.Header.Get("Idempotency-Key")
		writeStruct(w, 202, "", "queued", &types.CreateAppResponse{ID: 1})
	})
	_, err := c.Apps().Create(context.Background(), &types.CreateAppRequest{})
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	if len(key) < 16 {
		t.Errorf("Idempotency-Key: got %q (len=%d), want a generated key", key, len(key))
	}
}

func TestIdempotency_NotSentOnGET(t *testing.T) {
	var key string
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		key = r.Header.Get("Idempotency-Key")
		writeStruct(w, 200, "", "ok", &types.AppByIdResponse{Id: 1})
	})
	_, _, err := c.Apps().Get(context.Background(), 1)
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	if key != "" {
		t.Errorf("Idempotency-Key should not be sent on GET, got %q", key)
	}
}

func TestIdempotency_OverrideRespected(t *testing.T) {
	var seen string
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		seen = r.Header.Get("Idempotency-Key")
		writeStruct(w, 202, "", "queued", &types.CreateAppResponse{ID: 1})
	})
	_, err := c.Apps().Create(context.Background(), &types.CreateAppRequest{},
		client.WithIdempotencyKey("my-stable-key"))
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	if seen != "my-stable-key" {
		t.Errorf("Idempotency-Key: got %q, want %q", seen, "my-stable-key")
	}
}

func TestIdempotency_HeldConstantAcrossRetries(t *testing.T) {
	var keys []string
	var mu sync.Mutex
	var attempt atomic.Int32
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		keys = append(keys, r.Header.Get("Idempotency-Key"))
		mu.Unlock()
		a := attempt.Add(1)
		if a < 3 {
			writeStruct(w, 503, "", "transient upstream", nil)
			return
		}
		writeStruct(w, 202, "", "queued", &types.CreateAppResponse{ID: 1})
	})
	_, err := c.Apps().Create(context.Background(), &types.CreateAppRequest{})
	if err != nil {
		t.Fatalf("Create after retries: %v", err)
	}
	if len(keys) != 3 {
		t.Fatalf("expected 3 attempts, got %d", len(keys))
	}
	if keys[0] != keys[1] || keys[1] != keys[2] {
		t.Errorf("Idempotency-Key drifted across retries: %v", keys)
	}
}

// ── Retry policy ─────────────────────────────────────────────────────

func TestRetry_5xxThenSuccess(t *testing.T) {
	var attempt atomic.Int32
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		a := attempt.Add(1)
		if a < 3 {
			writeStruct(w, 503, "", "transient", nil)
			return
		}
		writeStruct(w, 200, "", "ok", &types.AppByIdResponse{Id: 7})
	})
	app, _, err := c.Apps().Get(context.Background(), 7)
	if err != nil {
		t.Fatalf("Get after retries: %v", err)
	}
	if app.Id != 7 {
		t.Errorf("Id: got %d, want 7", app.Id)
	}
	if attempt.Load() != 3 {
		t.Errorf("attempts: got %d, want 3", attempt.Load())
	}
}

func TestRetry_4xxNoRetry(t *testing.T) {
	var attempt atomic.Int32
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		attempt.Add(1)
		writeStruct(w, 404, codes.AppNotFound, "app not found", nil)
	})
	_, _, err := c.Apps().Get(context.Background(), 999)
	if err == nil {
		t.Fatal("expected error")
	}
	if !client.IsNotFound(err) {
		t.Errorf("IsNotFound: false, want true (err=%v)", err)
	}
	if attempt.Load() != 1 {
		t.Errorf("4xx should not retry, attempts=%d", attempt.Load())
	}
}

func TestRetry_IdempotencyInProgressRetries(t *testing.T) {
	var attempt atomic.Int32
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		a := attempt.Add(1)
		if a < 3 {
			writeStruct(w, 409, codes.IdempotencyInProgress, "still running", nil)
			return
		}
		writeStruct(w, 202, "", "queued", &types.CreateAppResponse{ID: 1})
	})
	_, err := c.Apps().Create(context.Background(), &types.CreateAppRequest{})
	if err != nil {
		t.Fatalf("Create after IN_PROGRESS retries: %v", err)
	}
	if attempt.Load() != 3 {
		t.Errorf("attempts: got %d, want 3", attempt.Load())
	}
}

func TestRetry_IdempotencyConflictNoRetry(t *testing.T) {
	var attempt atomic.Int32
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		attempt.Add(1)
		writeStruct(w, 409, codes.IdempotencyKeyConflict, "same key, different body", nil)
	})
	_, err := c.Apps().Create(context.Background(), &types.CreateAppRequest{})
	if err == nil {
		t.Fatal("expected error")
	}
	if !errors.Is(err, client.ErrIdempotencyKeyConflict) {
		t.Errorf("expected ErrIdempotencyKeyConflict, got %v", err)
	}
	if attempt.Load() != 1 {
		t.Errorf("KEY_CONFLICT must not retry (caller bug), attempts=%d", attempt.Load())
	}
}

func TestRetry_429HonorsRetryAfter(t *testing.T) {
	var attempt atomic.Int32
	var firstSeen, secondSeen time.Time
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		a := attempt.Add(1)
		if a == 1 {
			firstSeen = time.Now()
			w.Header().Set("Retry-After", "1")
			writeStruct(w, 429, "", "slow down", nil)
			return
		}
		secondSeen = time.Now()
		writeStruct(w, 200, "", "ok", &types.AppByIdResponse{Id: 1})
	})
	_, _, err := c.Apps().Get(context.Background(), 1)
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	gap := secondSeen.Sub(firstSeen)
	if gap < 900*time.Millisecond {
		t.Errorf("expected ~1s gap honoring Retry-After, got %v", gap)
	}
}

func TestRetry_NoRetryWhenDisabled(t *testing.T) {
	var attempt atomic.Int32
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		attempt.Add(1)
		writeStruct(w, 503, "", "transient", nil)
	}))
	defer srv.Close()
	c, err := client.New(srv.URL, client.WithAPIKey("kumo_sk_x"), client.WithRetries(0))
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	_, _, _ = c.Apps().Get(context.Background(), 1)
	if attempt.Load() != 1 {
		t.Errorf("WithRetries(0) should send exactly 1 attempt, got %d", attempt.Load())
	}
}

func TestRetry_CtxCancellationDuringBackoff(t *testing.T) {
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		writeStruct(w, 503, "", "transient", nil)
	})
	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		time.Sleep(20 * time.Millisecond)
		cancel()
	}()
	_, _, err := c.Apps().Get(ctx, 1)
	if !errors.Is(err, context.Canceled) {
		t.Errorf("expected context.Canceled, got %v", err)
	}
}

// ── ETag round-trip ──────────────────────────────────────────────────

func TestETag_GETReturnsHeader(t *testing.T) {
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("ETag", `W/"deadbeef"`)
		writeStruct(w, 200, "", "ok", &types.AppByIdResponse{Id: 1})
	})
	_, tag, err := c.Apps().Get(context.Background(), 1)
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	if tag != `W/"deadbeef"` {
		t.Errorf("etag: got %q, want %q", tag, `W/"deadbeef"`)
	}
}

func TestETag_PATCHSendsIfMatch(t *testing.T) {
	var got string
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		got = r.Header.Get("If-Match")
		writeStruct(w, 202, "", "queued", nil)
	})
	err := c.Apps().Update(context.Background(), 1, &types.UpdateAppRequest{},
		client.IfMatch(`W/"abc123"`))
	if err != nil {
		t.Fatalf("Update: %v", err)
	}
	if got != `W/"abc123"` {
		t.Errorf("If-Match: got %q, want %q", got, `W/"abc123"`)
	}
}

func TestETag_MismatchMapsToSentinel(t *testing.T) {
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		writeStruct(w, 412, codes.ETagMismatch, "stale", nil)
	})
	err := c.Apps().Update(context.Background(), 1, &types.UpdateAppRequest{},
		client.IfMatch(`W/"stale"`))
	if !errors.Is(err, client.ErrETagMismatch) {
		t.Errorf("expected ErrETagMismatch, got %v", err)
	}
}

func TestETag_EmptyIfMatchOmittedFromHeader(t *testing.T) {
	var got string
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		got = r.Header.Get("If-Match")
		writeStruct(w, 202, "", "queued", nil)
	})
	err := c.Apps().Update(context.Background(), 1, &types.UpdateAppRequest{},
		client.IfMatch(""))
	if err != nil {
		t.Fatalf("Update: %v", err)
	}
	if got != "" {
		t.Errorf("empty IfMatch should not send header, got %q", got)
	}
}

// ── Polling ──────────────────────────────────────────────────────────

func TestPollOperation_Success(t *testing.T) {
	var attempt atomic.Int32
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		a := attempt.Add(1)
		status := types.AppOperationStatusQueued
		switch a {
		case 1:
			status = types.AppOperationStatusQueued
		case 2:
			status = types.AppOperationStatusInProgress
		default:
			status = types.AppOperationStatusSucceeded
		}
		writeStruct(w, 200, "", "ok", &types.AppOperation{
			OperationID: "op-1", AppID: 7, Status: status,
		})
	})
	op, err := c.Apps().PollOperation(context.Background(), 7, "op-1",
		client.WithPollInterval(10*time.Millisecond),
	)
	if err != nil {
		t.Fatalf("PollOperation: %v", err)
	}
	if op.Status != types.AppOperationStatusSucceeded {
		t.Errorf("status: got %s, want succeeded", op.Status)
	}
	if attempt.Load() != 3 {
		t.Errorf("attempts: got %d, want 3", attempt.Load())
	}
}

func TestPollOperation_FailureSurfacesErrorCode(t *testing.T) {
	errCode := codes.AppQuotaExceeded
	errMsg := "image not found"
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		writeStruct(w, 200, "", "ok", &types.AppOperation{
			OperationID: "op-1", AppID: 7,
			Status:    types.AppOperationStatusFailed,
			ErrorCode: &errCode,
			ErrorMsg:  &errMsg,
		})
	})
	_, err := c.Apps().PollOperation(context.Background(), 7, "op-1",
		client.WithPollInterval(10*time.Millisecond),
	)
	if err == nil {
		t.Fatal("expected error from failed operation")
	}
	if !client.IsCode(err, codes.AppQuotaExceeded) {
		t.Errorf("expected IsCode(AppImagePullFailed), got %v", err)
	}
}

func TestPollOperation_RespectsCtxDeadline(t *testing.T) {
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		writeStruct(w, 200, "", "ok", &types.AppOperation{
			OperationID: "op-1", AppID: 7, Status: types.AppOperationStatusQueued,
		})
	})
	ctx, cancel := context.WithTimeout(context.Background(), 80*time.Millisecond)
	defer cancel()
	_, err := c.Apps().PollOperation(ctx, 7, "op-1",
		client.WithPollInterval(20*time.Millisecond),
	)
	if !errors.Is(err, context.DeadlineExceeded) {
		t.Errorf("expected DeadlineExceeded, got %v", err)
	}
}

func TestPollResource_Generic(t *testing.T) {
	count := 0
	final, err := client.PollResource(context.Background(),
		func(_ context.Context) (int, error) {
			count++
			return count, nil
		},
		func(v int) (bool, error) { return v >= 3, nil },
		client.WithPollInterval(5*time.Millisecond),
	)
	if err != nil {
		t.Fatalf("PollResource: %v", err)
	}
	if final != 3 {
		t.Errorf("final: got %d, want 3", final)
	}
}

// ── Concurrent safety ────────────────────────────────────────────────

func TestConcurrent_EachCallHasDistinctIdempotencyKey(t *testing.T) {
	var mu sync.Mutex
	keys := map[string]struct{}{}
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		key := r.Header.Get("Idempotency-Key")
		mu.Lock()
		keys[key] = struct{}{}
		mu.Unlock()
		writeStruct(w, 202, "", "queued", &types.CreateAppResponse{ID: 1})
	})
	var wg sync.WaitGroup
	const N = 10
	for i := 0; i < N; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			_, _ = c.Apps().Create(context.Background(), &types.CreateAppRequest{})
		}()
	}
	wg.Wait()
	mu.Lock()
	defer mu.Unlock()
	if len(keys) != N {
		t.Errorf("expected %d distinct keys, got %d (%v)", N, len(keys), keys)
	}
}

// ── Error decoding edge cases ────────────────────────────────────────

func TestError_EmptyBodyFallsBackGracefully(t *testing.T) {
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(503)
		// no body at all
	})
	_, _, err := c.Apps().Get(context.Background(), 1)
	if err == nil {
		t.Fatal("expected error")
	}
	var apiErr *client.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("expected *APIError, got %T (%v)", err, err)
	}
	// 503 is retryable, so we'll have exhausted retries first
	if apiErr.StatusCode != 503 {
		t.Errorf("StatusCode: got %d, want 503", apiErr.StatusCode)
	}
}

func TestError_NonJSONBodyFallsBackGracefully(t *testing.T) {
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/html")
		w.WriteHeader(502)
		_, _ = io.WriteString(w, "<html>nginx error</html>")
	})
	_, _, err := c.Apps().Get(context.Background(), 1)
	var apiErr *client.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("expected *APIError, got %T (%v)", err, err)
	}
	if !contains(apiErr.Message, "nginx") && apiErr.StatusCode != 502 {
		t.Errorf("expected message to include body snippet, got %q", apiErr.Message)
	}
}

// ── Apps service happy-path smoke ────────────────────────────────────

func TestApps_CRUDSmoke(t *testing.T) {
	var seenPath, seenMethod string
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		seenPath = r.URL.Path
		seenMethod = r.Method
		switch r.Method {
		case "POST":
			writeStruct(w, 202, "", "queued", &types.CreateAppResponse{ID: 42, Name: "demo"})
		case "GET":
			writeStruct(w, 200, "", "ok", &types.AppByIdResponse{Id: 42})
		case "PATCH":
			writeStruct(w, 202, "", "queued", nil)
		case "DELETE":
			writeStruct(w, 202, "", "queued", nil)
		default:
			http.Error(w, "unexpected method", 500)
		}
	})
	ctx := context.Background()

	created, err := c.Apps().Create(ctx, &types.CreateAppRequest{})
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	if created.ID != 42 {
		t.Errorf("Create ID: got %d, want 42", created.ID)
	}

	app, _, err := c.Apps().Get(ctx, 42)
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	if app.Id != 42 {
		t.Errorf("Get Id: got %d, want 42", app.Id)
	}

	if err := c.Apps().Update(ctx, 42, &types.UpdateAppRequest{}); err != nil {
		t.Fatalf("Update: %v", err)
	}
	if seenPath != "/api/v1/apps/42" || seenMethod != "PATCH" {
		t.Errorf("last call: %s %s, want PATCH /api/v1/apps/42", seenMethod, seenPath)
	}

	if err := c.Apps().Delete(ctx, 42); err != nil {
		t.Fatalf("Delete: %v", err)
	}
}

func TestApps_List(t *testing.T) {
	c, _ := newTestServer(t, func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Query().Get("page_size") != "5" {
			t.Errorf("page_size: got %q, want 5", r.URL.Query().Get("page_size"))
		}
		// Direct StructureResponse with Meta — encode manually because writeStruct doesn't support Meta.
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		_, _ = fmt.Fprint(w, `{"message":"ok","data":[{"id":1},{"id":2}],"meta":{"page":1,"page_size":5,"total_items":2,"total_pages":1}}`)
	})
	apps, meta, err := c.Apps().List(context.Background(), client.WithPageSize(5))
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	if len(apps) != 2 {
		t.Errorf("apps: got %d, want 2", len(apps))
	}
	if meta == nil || meta.TotalItems != 2 {
		t.Errorf("meta: %+v, want TotalItems=2", meta)
	}
}

// helpers
func contains(haystack, needle string) bool {
	return len(needle) == 0 || (len(haystack) >= len(needle) &&
		indexOf(haystack, needle) >= 0)
}

func indexOf(s, sub string) int {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}
